services:
  elixir:
    image: elixir:${ELIXIR_VERSION:-1.16}-alpine
    working_dir: /application/${ELIXIR_VERSION:-1.16}
    volumes:
      - .:/application/${ELIXIR_VERSION:-1.16}:cached
      - /application/${ELIXIR_VERSION:-1.16}/.elixir_ls
      - /application/${ELIXIR_VERSION:-1.16}/cover
      - build:/application/${ELIXIR_VERSION:-1.16}/_build
      - deps:/application/${ELIXIR_VERSION:-1.16}/deps
      - mix:/root/.mix
    entrypoint: tail -f /dev/null
    environment:
      POSTGRES_HOSTNAME: postgres

  postgres:
    image: postgres:17-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: supersecret
      POSTGRES_DB: charon_oauth2

volumes:
  build:
  deps:
  mix:
