name: CI / Automated testing
on:
  push:
    branches: ["**"]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Elixir ${{ matrix.elixir }} OTP ${{ matrix.otp }}
    env:
      MIX_ENV: test

    services:
      postgres:
        image: postgres:17-alpine
        env:
          POSTGRES_PASSWORD: supersecret
        ports:
          - 5432:5432

    strategy:
      # https://hexdocs.pm/elixir/1.19/compatibility-and-deprecations.html#between-elixir-and-erlang-otp
      matrix:
        include:
          - elixir: 1.16.x
            otp: 26.x
          - elixir: 1.19.x
            otp: 28.x

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}
      - name: Cache deps
        id: cache
        uses: actions/cache@v4
        with:
          path: |
            deps
            _build
          key: deps-cache-${{ matrix.elixir }}-${{ matrix.otp }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            deps-cache-${{ matrix.elixir }}-${{ matrix.otp }}-
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: mix do local.hex --force, local.rebar --force, deps.get
      - name: Check code formatting
        run: mix format --check-formatted
        # only check formatting on most recent Elixir version
        # to prevent failures because of formatter changes
        if: matrix.elixir == '1.19.x'
      - name: Compile dependencies
        run: mix deps.compile
      - name: Compile code (warnings as errors)
        run: mix compile --warnings-as-errors
      - name: Run tests
        run: mix test
      - name: Create docs
        run: mix docs
