name: CI / Automated testing
on:
  push:
    branches: ["**"]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Elixir ${{ matrix.elixir }} OTP ${{ matrix.otp }}
    env:
      MIX_ENV: test

    services:
      postgres:
        image: postgres:13-alpine
        env:
          POSTGRES_PASSWORD: supersecret
        ports:
          - 5432:5432
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379

    strategy:
      # https://hexdocs.pm/elixir/1.14/compatibility-and-deprecations.html#compatibility-between-elixir-and-erlang-otp
      matrix:
        elixir: [1.14.x, 1.17.x]
        otp: [24.x, 25.x, 27.x]
        exclude:
          - elixir: 1.14.x
            otp: 27.x
          - elixir: 1.14.x
            otp: 25.x
          - elixir: 1.17.x
            otp: 24.x

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}
      - name: Cache deps
        uses: actions/cache@v4
        with:
          path: |
            deps
            _build
          key: deps-cache-${{ matrix.elixir }}-${{ matrix.otp }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            deps-cache-${{ matrix.elixir }}-${{ matrix.otp }}-
      - name: Install dependencies
        run: mix do local.hex --force, local.rebar --force, deps.get
      - name: Check code formatting
        run: mix format --check-formatted
        # only check formatting on most recent Elixir version
        # to prevent failures because of formatter changes
        if: matrix.elixir == '1.17.x'
      - name: Compile dependencies
        run: mix deps.compile
      - name: Compile code (warnings as errors)
        run: mix compile --warnings-as-errors
      - name: Run tests
        run: mix test
      - name: Create docs
        run: mix docs
